apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpletimeservice
  labels:
    app: simpletimeservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpletimeservice
  template:
    metadata:
      labels:
        app: simpletimeservice
    spec:
      containers:
        - name: simpletimeservice
          image: nishdoc1999/simpletimeservice
          imagePullPolicy: IfNotPresent


