apiVersion: v1
kind: Service
metadata:
  name: simpletimeservice
spec:
  type: LoadBalancer
  selector:
    app: simpletimeservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      
